# Generated by Django 4.1.4 on 2022-12-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_message_inbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
